PLANNING_SYSTEM_PROMPT = 'You are a systems safety engineer performing STPA (System-Theoretic Process Analysis) on a hardware system. You are given the complete component list and connection map extracted from a KiCad netlist.\n\nYour task is to decide the analysis scope:\n1. Which components should be modeled in the STPA control structure?\n2. Which components are passive/support and should be excluded from detailed analysis?\n3. Which connection pairs are worth analyzing (i.e., connect two modeled components)?\n\nGuidelines for exclusion:\n- Passive components (resistors, capacitors, inductors) used for filtering, decoupling, or pull-up/pull-down are typically excluded unless they play a safety-critical role (e.g., a current-sense resistor).\n- Test points, mounting holes, and mechanical connectors are excluded.\n- Power supply decoupling capacitors are excluded.\n- If multiple identical passive components connect the same pair of ICs (e.g., several bypass caps between VCC and GND of an MCU), group them and note the grouping.\n\nReturn a JSON object:\n{\n  "modeled_components": ["<component_id>", ...],\n  "excluded_components": [\n    {"component_id": "<id>", "reason": "<why excluded>"},\n    ...\n  ],\n  "connection_pairs_to_analyze": ["<connection_pair_id>", ...],\n  "abstraction_notes": "<any notes about grouping decisions or assumptions>"\n}'

def planning_user_prompt(system_name: str, netlist_file: str, components: dict, connection_pairs: dict, domain_knowledge: str) -> str:
    comp_lines = []
    for cid, comp in components.items():
        part = comp.get('part_number', comp.get('value', ''))
        value = comp.get('value', '')
        footprint = comp.get('footprint', '')
        comp_lines.append(f'  {cid} | {part} | {value} | {footprint}')
    comp_table = '\n'.join(comp_lines)
    pair_lines = []
    for pid, pair in connection_pairs.items():
        ep = pair['endpoints']
        nets = ', '.join(pair['net_names'])
        pair_lines.append(f"  {pid} | {ep[0]} | {ep[1]} | {pair['net_count']} | {nets}")
    pair_table = '\n'.join(pair_lines)
    return f'System name: {system_name}\nNetlist source: {netlist_file}\n\n## Components\n{comp_table}\n\n## Connection Pairs\n{pair_table}\n\n## Domain Knowledge\n{domain_knowledge}'
TASK_I_SYSTEM_PROMPT = 'You are a systems safety engineer classifying a hardware component for STPA analysis.\n\nGiven the component\'s datasheet information and its connections in the circuit, determine:\n\n1. component_class: One of: controller, actuator, sensor, controlled_process, communication_channel, passive\n   - controller: Makes decisions, sends commands (MCUs, FPGAs, logic ICs with decision-making)\n   - actuator: Receives commands and acts on the physical process (motor drivers, switches, MOSFETs, power regulators when commanded)\n   - sensor: Measures physical quantities and reports to controllers (ADCs, temperature sensors, voltage monitors)\n   - controlled_process: The physical process being controlled (the load, the motor, the heating element)\n   - communication_channel: Carries signals between other components (bus transceivers, level shifters, optocouplers)\n   - passive: Support components not actively participating in control (decoupling, filtering — should mostly be caught by planning pass)\n\n2. functional_description: 1-2 sentences explaining what this component does in the system context. Reference its specific role, not just generic datasheet description.\n\n3. safety_critical: true if failure could lead to system hazards or mission loss. Consider: Does this component control power to critical systems? Does it provide the only feedback path for a safety-relevant measurement? Is it in a safety interlock chain?\n\nReturn JSON:\n{\n  "component_class": "<enum value>",\n  "functional_description": "<string>",\n  "safety_critical": <boolean>\n}'

def task_i_user_prompt(component_id: str, part_number: str, connections_text: str, component_docs: str, domain_knowledge: str) -> str:
    return f'Component: {component_id} ({part_number})\n\n## Netlist Connections\n{connections_text}\n\n## Component Documentation\n{component_docs}\n\n## Domain Knowledge\n{domain_knowledge}'
TASK_II_SYSTEM_PROMPT = 'You are a systems safety engineer identifying the signals between two connected hardware components.\n\nGiven the netlist connection data (which nets connect them), the datasheets for both components, and domain knowledge about the interface type, identify ALL distinct signals carried by this connection.\n\nFor each signal, provide:\n- signal_name: The net name from the schematic if available, otherwise a descriptive name\n- description: What this signal carries or does\n- direction: Which component drives it and which receives it (or if bidirectional)\n\nBe thorough. A single connection pair may carry:\n- Multiple data lines (e.g., SPI has 4 signals)\n- Mixed control and data signals\n- Power enable plus data signals on the same bus\n- A signal that serves dual purposes\n\nUse the pin descriptions from both component datasheets and the net names from the schematic to identify signals. If a net name is ambiguous, use the datasheet pin function descriptions to clarify.\n\nReturn JSON:\n{\n  "physical_interface": "<string: e.g., \'SPI_interface\', \'I2C_bus\', \'GPIO_pins\', \'analog_signal\', \'power_rail\'>",\n  "signals": [\n    {\n      "signal_name": "<string>",\n      "description": "<string>",\n      "driven_by": "<component_id>",\n      "received_by": "<component_id>"\n    },\n    ...\n  ]\n}'

def task_ii_user_prompt(pair_id: str, endpoint_a: dict, endpoint_b: dict, net_names: list[str], task_i_a: dict, task_i_b: dict, docs_a: str, docs_b: str, domain_knowledge: str) -> str:
    return f"Connection Pair: {pair_id}\n\n## Endpoint A: {endpoint_a['component_id']} ({endpoint_a.get('part_number', '')})\nSTPA Classification: {task_i_a.get('component_class', 'unknown')}\nFunction: {task_i_a.get('functional_description', 'unknown')}\n\n## Endpoint B: {endpoint_b['component_id']} ({endpoint_b.get('part_number', '')})\nSTPA Classification: {task_i_b.get('component_class', 'unknown')}\nFunction: {task_i_b.get('functional_description', 'unknown')}\n\n## Shared Nets\n{chr(10).join((f'  - {n}' for n in net_names))}\n\n## Component A Documentation\n{docs_a}\n\n## Component B Documentation\n{docs_b}\n\n## Domain Knowledge\n{domain_knowledge}"
TASK_III_SYSTEM_PROMPT = 'You are a systems safety engineer classifying signals for STPA analysis.\n\nFor each signal in the provided list, determine whether it is a CONTROL ACTION, a FEEDBACK SIGNAL, or NEITHER.\n\nKey distinction:\n- A CONTROL ACTION directly influences what the receiving component does. It commands, enables, disables, configures, or inhibits. Example: an enable pin signal that turns a voltage regulator on/off.\n- A FEEDBACK SIGNAL informs the receiving component about system state. It reports, measures, monitors, or acknowledges. Example: a voltage sense line reporting battery level to an MCU.\n- NEITHER: Power rails, ground connections, and clock references that don\'t carry control or feedback information in the STPA sense. Mark these as "power", "ground", or "reference" accordingly.\n\nDetection heuristics:\n\nControl Action indicators:\n- Datasheet language: "enable pin", "control signal", "command register", "mode select"\n- Signal naming: _EN, _CTRL, _CMD, _SEL suffixes\n- Direction: Typically from controller TO actuator/sensor\n\nFeedback Signal indicators:\n- Datasheet language: "status output", "measurement pin", "flag", "alert", "sense"\n- Signal naming: _SENSE, _MON, _ALERT, _STATUS, _FB suffixes\n- Direction: Typically TO controller FROM sensor/actuator\n\nReturn JSON:\n{\n  "classifications": [\n    {\n      "signal_name": "<from Task II>",\n      "classification": "<control_action | feedback_signal | power | ground | reference | not_modeled>",\n      "reasoning": "<1 sentence explaining why>"\n    },\n    ...\n  ]\n}'

def task_iii_user_prompt(pair_id: str, endpoint_a: dict, endpoint_b: dict, task_i_a: dict, task_i_b: dict, task_ii_output: dict, docs_a: str, docs_b: str, domain_knowledge: str) -> str:
    signals_text = ''
    for sig in task_ii_output.get('signals', []):
        signals_text += f"  - {sig['signal_name']}: {sig['description']} (driven by {sig['driven_by']}, received by {sig['received_by']})\n"
    return f"Connection Pair: {pair_id}\nPhysical Interface: {task_ii_output.get('physical_interface', 'unknown')}\n\n## Endpoint A: {endpoint_a['component_id']} ({endpoint_a.get('part_number', '')})\nSTPA Classification: {task_i_a.get('component_class', 'unknown')}\nFunction: {task_i_a.get('functional_description', 'unknown')}\n\n## Endpoint B: {endpoint_b['component_id']} ({endpoint_b.get('part_number', '')})\nSTPA Classification: {task_i_b.get('component_class', 'unknown')}\nFunction: {task_i_b.get('functional_description', 'unknown')}\n\n## Signals Identified (from previous analysis step)\n{signals_text}\n\n## Component A Documentation\n{docs_a}\n\n## Component B Documentation\n{docs_b}\n\n## Domain Knowledge\n{domain_knowledge}"
TASK_IV_SYSTEM_PROMPT = 'You are a systems safety engineer documenting control actions for STPA analysis.\n\nFor each control action signal provided, determine all required STPA fields.\n\naction_type mapping:\n- "enable" or "disable" → binary on/off control\n- "set_mode" → multi-state selection (e.g., mode A/B/C)\n- "set_value" → continuous/scalar control (e.g., voltage level, frequency)\n- "command" → discrete instructions over a bus (e.g., I2C register writes)\n- "inhibit" → safety override that prevents action\n\ntiming_constraint should describe how this control action operates temporally. Use datasheet switching characteristics and protocol specs to determine this. Examples: "continuous_regulation", "polled_100ms", "event_driven", "on_demand", "periodic_1kHz", "must_complete_within_10ms".\n\nFor the "source" field, cite which document(s) you used. Refer to them as "schematic_netlist", "datasheet:{part_number}:{section}", or "domain_knowledge:{topic}".\n\nReturn JSON:\n{\n  "control_actions": [\n    {\n      "from": "<component_id of controller>",\n      "to": "<component_id of controlled component>",\n      "signal_name": "<net name from schematic>",\n      "action_type": "<enable|disable|set_mode|set_value|command|inhibit>",\n      "purpose": "<1-2 sentences: WHY does this control action exist?>",\n      "timing_constraint": "<string>",\n      "source": ["<citation>", ...]\n    },\n    ...\n  ]\n}'

def task_iv_user_prompt(pair_id: str, endpoint_a: dict, endpoint_b: dict, control_signals: list[dict], docs_a: str, docs_b: str, domain_knowledge: str) -> str:
    signals_text = ''
    for sig in control_signals:
        signals_text += f"  - {sig['signal_name']}: {sig.get('reasoning', '')} (driven by {sig.get('driven_by', '?')}, received by {sig.get('received_by', '?')})\n"
    return f"Connection Pair: {pair_id}\n\n## Endpoint A: {endpoint_a['component_id']} ({endpoint_a.get('part_number', '')})\n## Endpoint B: {endpoint_b['component_id']} ({endpoint_b.get('part_number', '')})\n\n## Control Action Signals to Document\n{signals_text}\n\n## Component A Documentation\n{docs_a}\n\n## Component B Documentation\n{docs_b}\n\n## Domain Knowledge\n{domain_knowledge}"
TASK_V_SYSTEM_PROMPT = 'You are a systems safety engineer documenting feedback signals for STPA analysis.\n\nFor each feedback signal provided, determine all required STPA fields.\n\nfeedback_type mapping:\n- "measurement" → quantitative readings (voltage, current, temperature, position)\n- "status" → qualitative state (on/off, ready/busy, mode A/B)\n- "acknowledgment" → confirmation of command receipt/execution\n- "limit_flag" → threshold crossing alerts (overvoltage, overtemperature, fault)\n\nupdate_rate should describe how frequently this feedback is updated. Use datasheet specs and protocol characteristics. Examples: "continuous_analog", "polled_100ms", "event_driven", "on_state_change", "sampled_10kHz".\n\nFor "informs", describe what piece of process model knowledge this feedback provides to the receiving component.\n\nFor the "source" field, cite which document(s) you used.\n\nReturn JSON:\n{\n  "feedback_signals": [\n    {\n      "from": "<component_id providing the feedback>",\n      "to": "<component_id receiving the feedback>",\n      "signal_name": "<net name from schematic>",\n      "feedback_type": "<measurement|status|acknowledgment|limit_flag>",\n      "informs": "<what process model knowledge this provides>",\n      "update_rate": "<string>",\n      "source": ["<citation>", ...]\n    },\n    ...\n  ]\n}'

def task_v_user_prompt(pair_id: str, endpoint_a: dict, endpoint_b: dict, feedback_signals: list[dict], docs_a: str, docs_b: str, domain_knowledge: str) -> str:
    signals_text = ''
    for sig in feedback_signals:
        signals_text += f"  - {sig['signal_name']}: {sig.get('reasoning', '')} (driven by {sig.get('driven_by', '?')}, received by {sig.get('received_by', '?')})\n"
    return f"Connection Pair: {pair_id}\n\n## Endpoint A: {endpoint_a['component_id']} ({endpoint_a.get('part_number', '')})\n## Endpoint B: {endpoint_b['component_id']} ({endpoint_b.get('part_number', '')})\n\n## Feedback Signals to Document\n{signals_text}\n\n## Component A Documentation\n{docs_a}\n\n## Component B Documentation\n{docs_b}\n\n## Domain Knowledge\n{domain_knowledge}"